include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_locals: true
    
    # Performance rules
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    
    # Best practices
    use_key_in_widget_constructors: true
    prefer_single_quotes: false
    require_trailing_commas: true
